# Linux builds are only to make sure the project can be built w/ MinGW-w64 &
# GCC.

language: cpp
os: linux
dist: focal

env:
  global:
    boost_version: 1.65.0
  jobs:
    # Building only Debug is fine, it's not going anywhere anyway:
    - configuration=Debug   platform=x86
    - configuration=Debug   platform=x64
    #- configuration=Release platform=x86
    #- configuration=Release platform=x64

before_script:
  - cd cmake
  - >-
    python3 -m project.ci.travis.boost
    --mingw
    --
    --with-test

script: >-
    python3 -m project.ci.travis.cmake
    --install "$HOME/install"
    --mingw

jobs:
  fast_finish: true

  _clear: &clear
    language: minimal
    before_script: []
    script: []

  include:
    - <<: *clear
      name: Run clang-format
      if: branch = master
      addons:
        apt:
          packages:
            - clang-format-9
      script: ./cmake/tools/clang-format.py --clang-format clang-format-9
